### ISSUE TITLE
Better logging system

### ISSUE THREAD

**Issue by hilmoo** [warnet-gi/WarnetBot#139]
ref: 
[article1](https://fangpenlin.com/posts/2012/08/26/good-logging-practice-in-python/)
[article2](https://signoz.io/guides/python-logging-best-practices/)

**Comment by Iqrar99** [comment]
I think this size should be reduced as well to decrease the lines in the log file
https://github.com/warnet-gi/WarnetBot/blob/bfbab033cfcf8fe8de857320a74ba948f78c4ec1/bot/config/logger.py#L7-L12
