### ISSUE TITLE
Mute & Warn Feature Enhancement

### ISSUE THREAD

**Issue by athahibatullah** [warnet-gi/WarnetBot#20]
**Problem:**
Sistem warn dan mute yang merepotkan dan terlalu manual. Banyak member yang role warnnya nyangkut karena kelewatan/lupa dicopot secara manual.

**Solusi:**
Sebuah command untuk melakukan mute, warn, dan mencabut rolenya secara otomatis.
Nama commandnya:
`/warn member:[User Id] warn:[1 to 3] message:[Reason to warn]`

**Flowchart untuk add/update role user:**
![image](https://user-images.githubusercontent.com/31439960/209940925-cb3202ed-18fd-4395-b51c-fe9fd26d0a35.png)

**Desain Database:**
+---------+------------+------------+-------------+
| user_id | warn_level | date_given | date_expire |
+---------+------------+------------+-------------+

**Mencabut/menurunkan role member:**
1. Role dicabut kalo **warn 1** dan **current time > date expire**.
2. Role diturunin kalo **warn 2/3** dan **current time > date expire**. Lalu setelah diturunkan, date expire diupdate dengan waktu penurunan role barusan.

**Additional:**
1. Kalau member udah ketambah sampe warn 4, bot bakal ngereturn message ke user kalo member yang ditindak udah layak diban.
3. Log di bot diredirect ke channel #warn-log.
4. Kalo total warn nya masih warn 1, jangan dimute.

**Comment by Mozart165** [comment]
Desain db nya bisa tambahin reason sekalian maybe 
Desain Database:
+---------+------------+------------+-------------+-------------+
| user_id | warn_level | date_given | date_expire | reason |
+---------+------------+------------+-------------+-------------+

biar sesama admod tahu alasan ke warn kalau ada apa-apanya, biar praktis juga dalam satu tempat

**Comment by Iqrar99** [comment]
> Desain db nya bisa tambahin reason sekalian maybe Desain Database: +---------+------------+------------+-------------+-------------+ | user_id | warn_level | date_given | date_expire | reason | +---------+------------+------------+-------------+-------------+
> 
> biar sesama admod tahu alasan ke warn kalau ada apa-apanya, biar praktis juga dalam satu tempat

Oke noted. Soal db perlu gak ya ada state yang ngasih tahu dia lagi di server atau gk?

**Comment by athahibatullah** [comment]
Member leave:
-Pas udah expire date warnnya, pertama dicek dulu membernya lagi leave server apa gak
-Kalo lagi leave, dikasih flag di db nya leave_server = true
-Kalkulasi tetap berjalan meskipun dia leave server
-Kalo dah warn 0, jangan didelete dulu dari db, didelete dari db klo leave_server = false

Pas kembali join:
-User dicek ada di db gak
-Kalo dah warn 0 dan leave_server = false, bisa didelete dari db dan dicabut role warn nya
-Kalo masih ada warn, ubah leave_server = false terus turunin warn nya

Notes:
Jeleknya klo tiap orang yg join server mesti dicek di db

**Comment by Iqrar99** [comment]
Ok so far table db nya bakal gini.

* `user_id`: `BIGINT`
* `warn_level`: `INT`
* `date_given`: `TIMESTAMP`
* `date_expire`: `TIMESTAMP`
* `reason`: `VARCHAR`
* `leave_server`: `BOOLEAN`


| user_id | warn_level | date_given          | date_expire         | reason         | leave_server |
|---------|------------|---------------------|---------------------|----------------|--------------|
| 12345   | 1          | 2023-01-01 00:00:00 | 2023-02-01 00:00:00 | lorem ipsum    | 0            |
| 99999   | 3          | 2023-01-02 00:00:00 | 2023-02-02 00:00:00 | dolor sit amet | 1            |

**Comment by Iqrar99** [comment]
Refer to #21

**Comment by Iqrar99** [comment]
Refer to #21
