### ISSUE TITLE
Fix username display on embed

### ISSUE THREAD

**Issue by Iqrar99** [warnet-gi/WarnetBot#80]
Since Discord has changed its username system (no discriminator), the username display should omit `#0`.

<img width="512" alt="image" src="https://github.com/warnet-gi/WarnetBot/assets/20255031/73981be6-d47f-4ed5-8d23-8701500f74e4">

**Comment by rafiramadhana** [comment]
@Iqrar99 would you mind to point out the related code for displaying username?

i want to contribute for this issue

**Comment by Iqrar99** [comment]
Hi @rafiramadhana, thanks for the intention!
Some of the code are return the string representation of `Member` and `User` object by calling `str()` method like these:

https://github.com/warnet-gi/WarnetBot/blob/37cccba76f80c205b4d4e1a2bca37286ec815a7e/bot/cogs/khaenriah.py#L65

https://github.com/warnet-gi/WarnetBot/blob/37cccba76f80c205b4d4e1a2bca37286ec815a7e/bot/cogs/khaenriah.py#L88

https://github.com/warnet-gi/WarnetBot/blob/37cccba76f80c205b4d4e1a2bca37286ec815a7e/bot/cogs/general.py#L93

They are basically combine the username and discriminator in one place.

To omit the discriminator `#0` it should just return the `name` property from `Member` or `User`. The documentation is [here](https://discordpy.readthedocs.io/en/stable/api.html?highlight=member#discord.Member.name). Please let me know if you have any questions regarding this issue.

**Comment by rafiramadhana** [comment]
@Iqrar99 ok got it. thanks for the explanation

btw just want to confirm, the `ctx.author` will be updated to `ctx.author.name` right?

sry im not that familiar with the `Union[User, Member]:` term written in the [docs](https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.ext.commands.Context.author).

**Comment by Iqrar99** [comment]
`author` is the property of `Context`. It contains either `Member` or `User` object. `ctx.author` will be the same as `Member` or `User` depending how the context is invoked.
